### ISSUE TITLE
Unify sorting criteria

### ISSUE THREAD

**Issue by mikkotee** [funidata/hybridilusmu#12]
Tällä hetkellä paikallaolijat lista applikaatiossa on eri järjestyksessä kuin kanavalle tilatussa viestissä.

TODO:
Listataan paikallaolijat samassa järjejstyksessä molemmissa.
![Screenshot 2022-09-08 at 9 10 15](https://user-images.githubusercontent.com/30823893/189048159-08a051fe-46a4-4ae7-9c84-cb6c4423f921.png)

**Comment by joonashak** [comment]
### TODO:

- [ ] In all lists, use only full name when displaying user names. Name should link to the user's profile. If not possible, then add the username/handle after the full name: `Toni Sallanmaa (@Toni)`
- [ ] Sort all lists alphabetically.

**Comment by VoxBorealis** [comment]
Oversight: By adding user mentions to the scheduled messages, it will push unwanted notifications to the users.
Opening this issue again.

TODO: 

- [ ] Send the scheduled messages in a way that doesn't push notifications
