### ISSUE TITLE
Support multiple premises

### ISSUE THREAD

**Issue by mikkotee** [funidata/hybridilusmu#2]
Nyt kun Tampereen toimistolle on saatu lisää väkeä alkaa realisoitumaan tarve siitä, että voidaan määritellä millä toimistolla ollaan läsnä.

Mahdollisia featureita voisi olla
* toimipaikkojen hallinta (CRUD)
* henkilö voi määritellä oletuksena millä toimistolla käy
* yksittäiseen läsnäoloon voi määritellä millä toimistolla on läsnä
* läsnäolo tilaraportin (/tilaa) voi pyytää kuten nykyisin sekä lisäksi erikseen toimipaikkakohtaisesti, myös ryhmäkohtaisesti (`/tilaa <kellonaika> <tiimi> <toimipaikka>`)
* paikallaolijat voi listata kuten nykyisen sekä lisäksi erikseen toimipaikkakohtaisesti, myös ryhmäkohtaisesti (`/listaa <päivä> <tiimi> <toimipaikka>`)

**Comment by VoxBorealis** [comment]
Preliminary thoughts:

At the moment user signups are saved to the database table 'Signups', which include values for 'officeDate', 'atOffice (boolean)' and 'PersonId'. To support multiple premises, we need to:

- Create a new table for Offices
- Add a 'whichOffice' column to 'Signups' & 'Defaultsignups' tables
- Add a way for users to create new offices (slash commands / GUI?)
- Create an admin role for users so that not everyone can create new offices?
- On the app home tab, for each individual day -- add a way to select an office (dropdown?)
- On the 'Oletusasetukset'-modal add a way to select an office

Also... Should 'atOffice' value be turned in to a 'status' value, which would support multiple different statuses (Office, Remote, Absent)?

**Comment by joonashak** [comment]
I think this relates well to many things, including

- whether or not to replace Sequelize,
- whether or not to migrate to TypeScript and/or Nest.js,
- does current database design warrant other changes, and,
- do we have some very clear future requirements that can be used to shape the database design today.

We should probably spend a little time going over the current schema, identifying problems in it, and discussing the points above.

As to your questions about the UI/UX design, I think we should make a real quick prototype to see what feels best.

> Create an admin role for users so that not everyone can create new offices?

We can probably just lean on the roles users have in the Slack workspace. I.e., only workspace admins/owners can make changes to app-level settings.

**Comment by VoxBorealis** [comment]
**TODO:**

DB:

- [ ] Create table for Offices
- [ ] Add defaultOffice column to People table
- [ ] Add whichOffice column to Signups and Defaultsignups-tables (relation to Offices)

Front:

- [ ] Add dropdown menu for office selection to app home tab or to the 'oletusasetukset' modal (rename to 'asetukset'?)
- [ ] Only show list of registrations for the selected office
- [ ] If a user has registered to another office for a particular day, disable the registration button for that day (gray scale, hover text...)
- [ ] Same thing with default signup modal

Backend:

- [ ] Modify all registration and default registration service getters to include an office parameter. (perhaps an optional parameter? If no arg, then return all registrations)
- [ ] Check all calls to the above mentioned functions to see if office parameter is necessary.

Misc:

- [ ] Add a way to add offices (slash commands/GUI?)
