### ISSUE TITLE
Enable late registration

### ISSUE THREAD

**Issue by joonashak** [funidata/hybridilusmu#47]
### TODO:

- [x] Update old messages (only today):
  - [x] Messages sent to channels.
  - [ ] Private messages and/or command replies.
- [x] Users register their status via the same buttons regardless if it's early or late.
- [ ] This is probably a good thing to write an E2E test for?

**Comment by VoxBorealis** [comment]
Opened a [PR](https://github.com/funidata/hybridilusmu/pull/62) for this.

**Features:**
